TRAINING_DATA = [
    # Complaint
    ("the service was extremely slow", "Complaint"),
    ("customer support did not respond", "Complaint"),
    ("this app keeps crashing", "Complaint"),
    ("delivery was delayed again", "Complaint"),
    ("very disappointed with the performance", "Complaint"),
    ("system freezes frequently", "Complaint"),
    ("too many bugs in the application", "Complaint"),
    ("this update broke everything", "Complaint"),
    ("poor response from support team", "Complaint"),
    ("this experience is frustrating", "Complaint"),
    ("application is unstable after update", "Complaint"),
    ("facing frequent downtime", "Complaint"),
    ("service quality has degraded", "Complaint"),
    ("not happy with the recent changes", "Complaint"),
    ("nothing works as expected", "Complaint"),
    ("continuous errors are annoying", "Complaint"),
    ("support is unprofessional", "Complaint"),
    ("this feature does not work", "Complaint"),
    ("very poor performance overall", "Complaint"),
    ("completely dissatisfied with the service", "Complaint"),

    # Query
    ("how do i reset my password", "Query"),
    ("what are the pricing plans", "Query"),
    ("how can i upgrade my subscription", "Query"),
    ("where can i download invoices", "Query"),
    ("is offline mode available", "Query"),
    ("how long does verification take", "Query"),
    ("can i change my email address", "Query"),
    ("where is account settings located", "Query"),
    ("how do i contact customer support", "Query"),
    ("can you explain this feature", "Query"),
    ("what payment methods are supported", "Query"),
    ("how to enable notifications", "Query"),
    ("can i schedule a call", "Query"),
    ("is there a free trial", "Query"),
    ("how to cancel my plan", "Query"),
    ("can i get usage reports", "Query"),
    ("where can i update profile details", "Query"),
    ("how does billing work", "Query"),
    ("what is the refund policy", "Query"),
    ("is technical documentation available", "Query"),

    # Feedback
    ("design looks very modern", "Feedback"),
    ("performance has improved a lot", "Feedback"),
    ("interface is smooth and clean", "Feedback"),
    ("user experience feels better", "Feedback"),
    ("navigation is intuitive", "Feedback"),
    ("features are easy to find", "Feedback"),
    ("workflow is very logical", "Feedback"),
    ("application feels stable now", "Feedback"),
    ("loading speed is impressive", "Feedback"),
    ("overall experience is pleasant", "Feedback"),
    ("nice improvement in performance", "Feedback"),
    ("this update made things better", "Feedback"),
    ("interface design is excellent", "Feedback"),
    ("response time has improved", "Feedback"),
    ("app is much faster now", "Feedback"),
    ("everything feels more polished", "Feedback"),
    ("the layout is well structured", "Feedback"),
    ("system feels optimized", "Feedback"),
    ("very smooth user journey", "Feedback"),
    ("great overall enhancement", "Feedback"),

    # Appreciation
    ("thank you for the quick help", "Appreciation"),
    ("excellent customer support", "Appreciation"),
    ("great service from the team", "Appreciation"),
    ("i appreciate your assistance", "Appreciation"),
    ("very satisfied with the support", "Appreciation"),
    ("thanks for resolving my issue", "Appreciation"),
    ("wonderful service experience", "Appreciation"),
    ("outstanding response time", "Appreciation"),
    ("support team was very helpful", "Appreciation"),
    ("keep up the great work", "Appreciation"),
    ("many thanks for your guidance", "Appreciation"),
    ("really appreciate your effort", "Appreciation"),
    ("excellent follow up", "Appreciation"),
    ("great job on this update", "Appreciation"),
    ("very grateful for the help", "Appreciation"),
    ("impressed by the service quality", "Appreciation"),
    ("thank you for your patience", "Appreciation"),
    ("fantastic experience overall", "Appreciation"),
    ("superb customer service", "Appreciation"),
    ("highly appreciate the support", "Appreciation"),

    # General Conversation
    ("hello there", "General_Conversation"),
    ("good morning", "General_Conversation"),
    ("hope you are doing well", "General_Conversation"),
    ("nice talking to you", "General_Conversation"),
    ("how is everything going", "General_Conversation"),
    ("let us discuss later", "General_Conversation"),
    ("just checking in", "General_Conversation"),
    ("that sounds interesting", "General_Conversation"),
    ("looking forward to it", "General_Conversation"),
    ("let me know your thoughts", "General_Conversation"),
    ("hope to hear from you soon", "General_Conversation"),
    ("good evening", "General_Conversation"),
    ("have a great day", "General_Conversation"),
    ("pleased to meet you", "General_Conversation"),
    ("wish you all the best", "General_Conversation"),
    ("talk to you later", "General_Conversation"),
    ("enjoy your day", "General_Conversation"),
    ("take care", "General_Conversation"),
    ("nice chatting with you", "General_Conversation"),
    ("catch up soon", "General_Conversation")
]
